apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubernetes-test-app
  template:
    metadata:
      labels:
        app: kubernetes-test-app
    spec:
      containers:
      - name: kubernetes-test-app
        image: kubernetes-test-app:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry(any cloud repository) search within the kubernetes cluster
        # imagePullPolicy: Always #(if you want to pull from a registry(e.g., Docker Hub, AWS ECR, etc.))
        # image: AWSrepo-link/kubernetes-test-app:latest #(if you want to pull from a registry(e.g., Docker Hub, AWS ECR, etc.))
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  ports:
  - port: 5000
    targetPort: 8080